<!-- footer inc-->
    <script src="//ossweb-img.qq.com/images/js/jquery/jquery-1.11.3.min.js"></script>
    <script src="//ossweb-img.qq.com/images/js/title.js"></script>
    <script  src="//game.gtimg.cn/images/js/2018foot/foot.js"></script>
    <script src="//ossweb-img.qq.com/images/js/PTT/ping_tcss_tgideas_https_min.js"></script>
    <script src="//ossweb-img.qq.com/images/js/swiper/swiper-3.4.2.min.js"></script>
    <script src='//vm.gtimg.cn/tencentvideo/txp/js/txplayer.js'></script>
    <script src="js/common.js"></script>
    <!-- footer end-->
