<!-- meta inc-->
    <meta charset="gbk" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="robots" content="all">
    <meta name="author" content="Tencent-CP" />
    <meta name="Copyright" content="Tencent" />
    <!-- QQ分享 -->
    <meta itemprop="name" content="分享标题">
    <meta itemprop="description" content="摘要：必填 长度至少为10" />
    <meta itemprop="image" content="图片地址不可为空，项目组无法提供的情况下，默认放游戏logo">
    <meta name="Keywords" content="页面关键字"/>
    <meta name="Description" content="页面的描述内容" />
    <link rel="stylesheet" href="//ossweb-img.qq.com/images/js/swiper/swiper-3.4.2.min.css">
    <link rel="stylesheet" href="css/common.css">
    <title>专题主题（标题）- 产品中文全称官方网站 - 腾讯游戏</title>
    <!-- 页面设计：世嘉 | 页面制作：世嘉 | 创建：****-**-** -->
    <script>
        //PC跳转移动端
        (function () {
            if ((navigator.userAgent.match(/(phone|pad|pod|iPhone|iPod|ios|iPad|Android|Mobile|BlackBerry|IEMobile|MQQBrowser|JUC|Fennec|wOSBrowser|BrowserNG|WebOS|Symbian|Windows Phone)/i))) {
                // window.location.href = "";
            }
        }())
    </script>
    <!-- meta end-->
