<!-- meta inc-->
    <meta charset="gbk" />
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <!-- 为了防止页面数字被识别为电话号码，可根据实际需要添加： -->
    <meta name="format-detection" content="telephone=no">
    <!-- 让添加到主屏幕的网页再次打开时全屏展示，可添加：   -->
    <meta content="yes" name="mobile-web-app-capable">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="robots" content="all">
    <meta name="author" content="Tencent-CP" />
    <meta name="Copyright" content="Tencent" />
    <meta name="Description" content="页面的描述内容" />
    <meta name="Keywords" content="页面关键字" />
    <link rel="stylesheet" href="//ossweb-img.qq.com/images/js/swiper/swiper-3.4.2.min.css">
    <link rel="stylesheet" href="css/common.css">
    <title>专题主题（标题）- 产品中文全称官方网站 - 腾讯游戏</title>
    <!-- 页面设计：cp | 页面制作：cp | 创建：2020-05-20 -->
    <script>
        if(!/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)) {
            // window.location.href = "PC端专题地址"+location.search;
        }
    </script>
    <!-- meta end-->
